services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=productdb
    depends_on:
      - product-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=product-db", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=cart-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=cartdb
      - APP_ENV=docker
    depends_on:
      - cart-db
    healthcheck:
      test: ["CMD", "pg_isready", "--host=cart-db", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    command: bash -c "php artisan migrate && php -S 0.0.0.0:3002 -t public"


  product-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productdb
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cart-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cartdb
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s


volumes:
  product-db-data:
  cart-db-data:
